### ISSUE TITLE
Registration/Login

### ISSUE THREAD

**Issue by slashmili** [elixir-berlin/juntos#5]
We'd like to provide authentication using:
* [Github](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/)
* [Twitter](https://developer.twitter.com/en/docs/basics/authentication/overview/oauth)
* [LinkedIn](https://docs.microsoft.com/en-gb/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin) (optional)
* [Apple](https://developer.apple.com/sign-in-with-apple/) Looks complicated! (optional)
* [dribbble](https://developer.dribbble.com/v1/oauth/) (if one day we target designers!) (optional)
* Facebook(optional)
* Google(optional)

# Auth Flow
Registration and login are part of this flow, if this is the first time that we are seeing this user, we create an account for them, otherwise just return the session.
![Auth flow](https://user-images.githubusercontent.com/585764/70004973-5e3c1780-1568-11ea-9ddd-7cb50670ef1f.png)

# APIs

* getAuthMethods : returns list of oatuh methods with:
    * auth type (ex, github/twitter)
    * client_id (ex ad6564bf-65b0-418c-b86a-573f1fc6b8f2)
    * scope (ex "email name")
   * auth_url (ex https://api.twitter.com/oauth/authorize)
    
* createSession: accepts OAuth temporary code and login/register users and return JWT token along with user info

# Schemas

## User
* id(uuid)
* name
* email (maybe we should detect if the user is new or not based on the email, this allows people to login using multiple oauth server and still have the same account)
* username(unique)
* social: {twitter: ..., github:...., ....} (we can fill this up when they use an oauth service to login)
## User-OAuth
* UserID
* OAuth Provider
* Access token (it's better to not store this!)
* Refresh token (it's better to not store this!)
* expires at (it's better to not store this!)

Not sure of we need User-OAuth schema at all!

**Comment by duksis** [comment]
I think facebook auth could be also relevant, but that we can find out from users once this is implemented.
Do you have ideas of what libraries frameworks to use for this?

**Comment by slashmili** [comment]
We can add facebook and google, I thought we can go for github first since our first target is developers

this the library that I used before https://github.com/scrogson/oauth2
